### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by DamienCassou** [emacs-lsp/lsp-haskell#104]
HI,

:warning: I'm learning haskell and have barely any experience with LSP. 

I think some documentation to get started is missing.

When LSP sends me a message such as

> Top-level binding with no type signature

is it possible to automatically add the type (which is included in the error message) to my file without copy/pasting?

Some more questions related to documentation:
- how to automatically add imports (`M-x lsp-organize-imports` doesn't work)?
- how to start a REPL bound to the current buffer?

**Comment by michaelpj** [comment]
These are server issues, please have a look at `haskell-language-server`, which additionally has more documentation.

For your particular issues, see:
- https://github.com/haskell/haskell-language-server/issues/719
- https://github.com/haskell/haskell-language-server/issues/477

**Comment by DamienCassou** [comment]
Understood, thank you!
