### ISSUE TITLE
`lsp-ui` - needed or not?

### ISSUE THREAD

**Issue by timo-a** [emacs-lsp/lsp-haskell#107]
The current README contains the line
```
Note: All three packages are also available via MELPA.
```
But it is unclear what the third package is (I cannot find `lsp` in melpa).

Looking through the file history, in commit 778f816 the line
```
Note: All three packages are also available via MELPA.
``` 
is added along with `(require 'lsp-ui)`  

In commit 5c22b808 `lsp-ui` is removed but the reference to `three packages` is kept.

So I'm 97% sure the line is outdated can just be corrected to "two" or dropped altogether. But on that note, is `lsp-ui` really no longer needed?

**Comment by michaelpj** [comment]
I think you're right. I also think you may not need to actively require `lsp-haskell`, I think `lsp-mode` does it. Let me see if I can cut it down a bit.
