### ISSUE TITLE
Error applying HLint suggestions

### ISSUE THREAD

**Issue by soylens** [emacs-lsp/lsp-haskell#11]
Enter Recursive editing using [M-x lsp-apply-commands], after pressing [C-c C-c], Error `Invalid function: lsp--intero-with-temp-buffer`
OS: Fedora 27 in Hyper-V VM
Emacs: 25.3 in terminal

**Comment by michaelpj** [comment]
I think this is quite out of date, I can't see any references to such a function in `lsp-haskell`, `lsp-mode`, or `haskell-mode`.
