### ISSUE TITLE
File mode specification error: (void-function -compose)

### ISSUE THREAD

**Issue by jwaldmann** [emacs-lsp/lsp-haskell#114]
Hi. I am trying to use lsp-haskell. I have a built haskell-language-server(-wrapper), I have configured emacs. When loading a hs source file (in the top directory of a stack project with hie.yaml), emacs says
```
File mode specification error: (void-function -compose)
```
I found https://emacs.stackexchange.com/questions/63621/how-do-i-solve-lisp-error-void-function-compose-when-using-lsp-dart but I'm not sure what to make of it. `package-install` does not show  a `dart` package (but several `dart-*`).

When I say `M-x lsp-mode`, I get `(Haskell LSP[Disconnected] ...)` in the mode line. (Is this a separate error?)

**Comment by jcs090218** [comment]
See https://github.com/emacs-lsp/lsp-mode/issues/2615.

Make sure you update package `dash` to the latest version.

**Comment by jwaldmann** [comment]
Oh sorry, then I close this as duplicate.
