### ISSUE TITLE
preview of changes for "apply hint(s)"?

### ISSUE THREAD

**Issue by jwaldmann** [emacs-lsp/lsp-haskell#116]
How can I pre-view the changes that "apply hint" would bring? Without actually changing the buffer/file, I mean. 

If that's not possible - is there an easy and failsafe way to revert them? (C-X U?)

**Comment by yyoncho** [comment]
there is  this: https://github.com/emacs-lsp/lsp-mode/issues/316

**Comment by jwaldmann** [comment]
OK so you mean it's already on the wishllist, and this repo (lsp-haskell) is the wrong place to ask (since it's not Haskell-specific)? Feel free to close if that's the case. And, thank you for the quick response.

**Comment by yyoncho** [comment]
Not that is wrong, but better to be handled in lsp-mode core.

**Comment by michaelpj** [comment]
Yes, this is about the generic Emacs LSP support, so it's a `lsp-mode` concern.

I believe there may also be a `haskell-language-server` issue to use the `changeAnnotations` support which I think enables this.
