### ISSUE TITLE
what hints are "all hints"?

### ISSUE THREAD

**Issue by jwaldmann** [emacs-lsp/lsp-haskell#117]
There are situations where I see "Apply all hints" but I don't know what these are (and where they'd be applied, #116)

![Screenshot_2021-03-09_17-44-21](https://user-images.githubusercontent.com/1334345/110506279-3c342c00-80ff-11eb-90a9-cc977d42c4e2.png)

**Comment by michaelpj** [comment]
Hi, this is either about the code action `haskell-language-server` produces, or about how `lsp-mode` shows it to you, so please open an issue in the appropriate repository as per the README: https://github.com/emacs-lsp/lsp-haskell#troubleshooting

**Comment by jwaldmann** [comment]
Thanks. Either - or: Would you have a guess on which it is?

**Comment by michaelpj** [comment]
Well, I'm not sure quite what you'd like to happen. The other issue was about previewing the changes, which I think is a `lsp-mode` issue. Is it that you want the message to be something like "Apply all hints in this file"? Then that would be a `haskell-language-server` issue.

**Comment by jwaldmann** [comment]
I was hoping there is a way to see the actual list of hints. (Later I want to preview their application, but first I want to just see their names.)

![Screenshot_2021-03-09_18-45-48](https://user-images.githubusercontent.com/1334345/110514544-b23c9100-8107-11eb-8883-4cfb33d3dc3b.png)

Sometimes it looks like the above - then I assume "make all imports explicit" is a subset of "all hints".

**Comment by michaelpj** [comment]
I think you probably want to open something in `haskell-language-server`! It seems like there are a few things that could be improved:
- The "Apply all hints" message doesn't specify that it's talking about a) hlint hints, b) all the hlint hints in the file
- There isn't a way to see all the hlint hints in the buffer from the message. I'm not sure if there's anything we can easily do about this, but perhaps someone will have an idea. The edit previewing might have to do the job if they implement that on the `lsp-mode` side.

**Comment by jwaldmann** [comment]
Thanks, will do.
