### ISSUE TITLE
(macOS)Flycheck doesnt work

### ISSUE THREAD

**Issue by soylens** [emacs-lsp/lsp-haskell#12]
Flycheck results flashes and disappears.(with [M-x flycheck-list-errors])
I hooked flycheck-mode to lsp-mode-hook. All components up-to-date.

**Comment by soylens** [comment]
![emacs-bug](https://user-images.githubusercontent.com/5269127/35790879-897e5b4c-0a7f-11e8-80e8-f6d692e73c5d.gif)
This is a preview(i cannot capture screen well)
anyways thost results only appear for a small period of time when i typed a new line in

**Comment by michaelpj** [comment]
Hi, this is from quite a long time ago. As far as I can tell, flycheck seems to work well with `lsp-mode` now. Please do reopen if you're still using the project and you observe this again!
