### ISSUE TITLE
Unable to get code completion or other lsp features

### ISSUE THREAD

**Issue by F15Ky** [emacs-lsp/lsp-haskell#122]
Output of haskell-language-server --probe-tools or haskell-language-server-wrapper --probe-tools:

cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.10.4

I am running doom emacs. 

Tested with multiple projects including a basic one with just cabal init.
It says it has connected to server. when running M-x lsp.

Here are the logs:
https://gist.github.com/F15Ky/69e242397f60575147460afe9262c7f8

Please let me know if you require further information.

**Comment by michaelpj** [comment]
Hi, I see you've already opened an issue for this in `haskell-language-server`, which is the right place for this. Duplicating it won't help :)
