### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by ilitzroth** [emacs-lsp/lsp-haskell#124]
Debugger entered--Lisp error: (error "Keyword argument :major-modes not one of (:languag...")
  signal(error ("Keyword argument :major-modes not one of (:languag..."))
  error("Keyword argument %s not one of (:language-id :send..." :major-modes)
  make-lsp--client--cmacro((make-lsp--client :new-connection (lsp-stdio-connection (lambda nil (lsp-haskell--server-command))) :major-modes '(haskell-mode haskell-literate-mode) :server-id 'lsp-haskell :initialized-fn (lambda (workspace) (with-lsp-workspace workspace (lsp--set-configuration (lsp-configuration-section "haskell")))) :language-id "haskell" :completion-in-comments\? t) :new-connection (lsp-stdio-connection (lambda nil (lsp-haskell--server-command))) :major-modes '(haskell-mode haskell-literate-mode) :server-id 'lsp-haskell :initialized-fn (lambda (workspace) (with-lsp-workspace workspace (lsp--set-configuration (lsp-configuration-section "haskell")))) :language-id "haskell" :completion-in-comments\? t)

**Comment by yyoncho** [comment]
you somehow are using 2+ years old version of lsp-mode - :language-id param was dropped long time ago.

**Comment by ilitzroth** [comment]
Yep, found that out. I had an outdated straight version of lsp-mode.
Maybe some kind of versioning check is possible.
Thanks for the speedy reply.

**Comment by michaelpj** [comment]
Sounds like you worked it out!
