### ISSUE TITLE
Disabling completion snippets does not work (anymore)

### ISSUE THREAD

**Issue by hpdeifel** [emacs-lsp/lsp-haskell#126]
Setting `lsp-haskell-completion-snippets-on` to `nil` (and restarting the server) has no effect when using the latest `haskell-language-server` (1.2.0).

This is probably caused by https://github.com/haskell/haskell-language-server/pull/1619 which was introduced in 1.1.0 and changed the setting name from `haskell.completionSnippetsOn` to the intuitively named `haskell.plugin.ghcide-completions.config.snippetsOn`.

---
Doing

```elisp
(lsp-register-custom-settings
  '(("haskell.plugin.ghcide-completions.config.snippetsOn" lsp-haskell-completion-snippets-on t)))
```

worked for me to fix it.

**Comment by michaelpj** [comment]
Thanks, good point, we need to regenerate all these things to make them match the new config options.

Of course, that will break old HLSs, but I don't think we can realistically keep compatibility, especially given the pace of change right now. Caveat emptor!

**Comment by michaelpj** [comment]
Fixed, finally.
