### ISSUE TITLE
Only able to run over TRAMP with lsp-log-io set to t

### ISSUE THREAD

**Issue by nosewings** [emacs-lsp/lsp-haskell#127]
Emacs 27; this is the relevant section of my init:

```emacs-lisp
(lsp-register-client
  (make-lsp--client
    :new-connection (lsp-tramp-connection (lambda () (lsp-haskell--server-command)))
    :major-modes '(haskell-mode haskell-literate-mode)
    :server-id 'lsp-haskell-remote
    :initialized-fn (lambda (workspace)
                      (with-lsp-workspace workspace
                        (lsp--set-configuration (lsp-configuration-section "haskell"))))
    :language-id "haskell"
    :completion-in-comments? t
    :remote? t))

(with-eval-after-load "tramp"
  (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
```

If I try to edit a file over SSH, I get a message that the LSP server exited. The output at /tmp doesn't give any useful information; it seems to just report that the server started successfully. Weirdly, when I set `lsp-log-io` to `t`, the server actually runs. This is a good thing, but it also makes it hard to figure out what's going wrong.

**Comment by yyoncho** [comment]
most likely duplicate of https://github.com/emacs-lsp/lsp-mode/issues/2709

**Comment by nosewings** [comment]
Ah, so it is.
