### ISSUE TITLE
Feature: insert type for top level definition

### ISSUE THREAD

**Issue by IvanMalison** [emacs-lsp/lsp-haskell#13]
Like `intero-type-at` with insertion argument

**Comment by MaskRay** [comment]
This can be implemented as a textDocument/codeAction method.

**Comment by IvanMalison** [comment]
@MaskRay Can you elaboroate on exactly how you would imagine this should be implemented?

I was thinking the actual code insertion would be handled on the emacs side of things.

**Comment by MaskRay** [comment]
I guess the workflow is:

user: insert-type
client: `textDocument/codeAction` request
server: `Command[]` response
client: `workspace/executeCommand` with the `Command[]`
server: `workspace/applyEdit` response
client: apply changes to the buffer

I am not sure I have not fully implemented this in cquery/ccls (my fork)

**Comment by wedens** [comment]
How do I make this action to appear? I don't have any hints to add a type to top level signature.

I use the HEAD lsp-haskell and hie.

**Comment by alanz** [comment]
@wedens are you using `lsp-ui` as well? It should show up in the sideline.

**Comment by wedens** [comment]
yes. it shows other hints like lift, demote, etc

**Comment by alanz** [comment]
Adding a type signature only shows up if GHC is generating a warning for it. Does your project have that warning enabled? i.e. do you get a GHC warning on line 15 saying it does not have a type signature?

**Comment by wedens** [comment]
No, I don't have a warning. Looks like `-fwarn-missing-signatures` is not included in `-Wall`. 

Ok, can we have a feature that adds a type signature for any definition under cursor? :)

**Comment by alanz** [comment]
I suggest you open an issue on haskell-ide-engine for that.

**Comment by wedens** [comment]
Turns out it already exists https://github.com/haskell/haskell-ide-engine/issues/787

**Comment by michaelpj** [comment]
I don't know if there's an issue for this in `haskell-language-server` now, but if it's still a problem there should be an issue there.
