### ISSUE TITLE
Mouse scrolling stuck with large code lens

### ISSUE THREAD

**Issue by yaitskov** [emacs-lsp/lsp-haskell#137]
Hi,

Import with long list of highlighted names which are actually used in the file prevent mouse scrolling.
Looks like additionally generated lines are not counted correctly.
Meanwhile keyboard cursor navigation is working.

![highlighted-imports](https://user-images.githubusercontent.com/1292734/140597255-cc1721eb-9ac3-447f-96e3-e44ffa4e5ea1.png)

```
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.16.0)
  lsp-haskell        20210813.1040 dependency            Haskell support for lsp-mode
  lsp-mode           20211103.1331 dependency            LSP mode
  lsp-ui             20211101.131  dependency            UI modules for lsp-mode
```

**Comment by yyoncho** [comment]
By "prevent scrolling" you mean that you cannot go down with the mouse? 

> Looks like additionally generated lines are not counted correctly.

What do you mean?

**Comment by michaelpj** [comment]
This is an issue with `lsp-mode`, and the thing you are having trouble with is a code lens.

**Comment by JonathanReeve** [comment]
I'm having this same issue, and I'd like to add that scrolling is also stuck whenever you wankt to page up or page down through code, using the keyboard (C-f and C-b in Evil, or pgup / pgdown on the keyboard).

**Comment by michaelpj** [comment]
I suspect the issue here is ultimately with code lenses that span multiple lines?

**Comment by michaelpj** [comment]
The HLS lenses are now trimmed, so this shouldn't come up any more.
