### ISSUE TITLE
Please, can inferred types be copied to clipboard

### ISSUE THREAD

**Issue by Anton-Latukha** [emacs-lsp/lsp-haskell#139]
Currently, there are numerous cases when types that are inferred (for instance declarations, for local functions, for typed holes) are shown in floating minibuffer, but can not be copied to search information on them.

![Screenshot-2021-11-19-22:02:56](https://user-images.githubusercontent.com/20933385/142684784-eb429460-341c-4d76-a96f-f2a700ccc902.png)

As a regular user I need to manually remember, & retype `IOEnv (Env TcGblEnv TcLclElv) a -> IO a` in a separate virtual monitor to websearch.

If something - I know where are the inferred type signatures are in the HLS. But seems like that info is provided into Emacs & also can be retrieved in it.

An inferred signature retrieval key combination would be of immense help.

**Comment by yyoncho** [comment]
FYI there is M-x lsp-describe-thing-at-point which will open a buffer supporting copying.

**Comment by Anton-Latukha** [comment]
Yup.

It is hidden in `Spacemacs` in `h` (help) submenu (`, h h`).

Good enough for me. But separate function would been even awesomer (*sic). It asks to exist when project would have #129 ability.

**Comment by yyoncho** [comment]
JFYI you can use `K` in spacemacs as well.

**Comment by Anton-Latukha** [comment]
Never knew of these short key combinations, `K` is not in the Spacemacs [`development Haskell layer docs`](https://develop.spacemacs.org/layers/+lang/haskell/README.html) nor in [`development LSP layer docs`](https://develop.spacemacs.org/layers/+tools/lsp/README.html) & *idk* how to search/see all currently loaded Emacs keybinds in the keymap.

**Comment by yyoncho** [comment]
It is in top level spacemacs convention. `K` = `,hh`; `gd = ,gg`
