### ISSUE TITLE
Headscratching class plugin experience

### ISSUE THREAD

**Issue by hellwolf** [emacs-lsp/lsp-haskell#153]
Hi,

I have enjoyed using lsp-mode a lot, been a treat!

A recent update of lsp "master" branch code had me a bit head scratching, and resulted me to disable it for now:

```elisp
(use-package lsp-haskell
  :config
  (add-hook 'lsp-after-initialize-hook
            #'(lambda ()
                (lsp--set-configuration
                 `(:haskell (:plugin (:class (:codeLensOn 0))))
                 ))))

```

The behavior is that the instance signature codeLens clutters my source code, and often I mis-click some and then it modifies the code for me:

![image](https://user-images.githubusercontent.com/186660/184648655-c1f02c66-e9fa-4feb-ad18-fca11cdfded6.png)

Related discussion at: https://github.com/haskell/haskell-language-server/discussions/3105

I am curious how you all think of this.

Cheers,

**Comment by hellwolf** [comment]
I'd definitely prefer the default setting that means having it on.

**Comment by hellwolf** [comment]
actually

```elisp
(use-package lsp-haskell
  :config
  (add-hook 'lsp-after-initialize-hook
          (lambda ()
            (lsp--set-configuration
              '(:haskell (:plugin (:class (:codeLensOn false))))
              ))))
```

didn't work :(

**Comment by yyoncho** [comment]
set  lsp-lens-enable to nil

**Comment by hellwolf** [comment]
I think make them only expand only when clicked with a modifier key pressed could be an option?

**Comment by michaelpj** [comment]
Looking at the HLS issue, it seems that there already is an option, we just don't expose it in `lsp-haskell`. Unfortunately, we have to manually regenerate the `defcustom`s for all the options as new ones are added, so it just needs someone to do the work. PRs welcome!

**Comment by hellwolf** [comment]
>  we have to manually regenerate the defcustoms for all the options as new ones are added, so it just needs someone to do the work. PRs welcome!

I wouldn't mind doing the PR, but I don't know how to generate, is it:

```
https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-generate-settings.el
```


Though I'd still prefer not to disable the feature if it gets a better "UX" :)

**Comment by michaelpj** [comment]
We updated the config, so this should be configurable now.
