### ISSUE TITLE
Hlint

### ISSUE THREAD

**Issue by arademaker** [emacs-lsp/lsp-haskell#155]
How can I configure (or make sure it is already configured) the use of hlint plugin ?

**Comment by arademaker** [comment]
Maybe too silly question? But I really don't know how to confirm if hlint is running in my file... any idea?

**Comment by michaelpj** [comment]
Sadly I don't think there's an easy way for servers to list such things in a way the client can see. The easiest test would be to write some code where a hint should apply and see if you get a diagnostic!

**Comment by michaelpj** [comment]
Not sure there's anything to do here
