### ISSUE TITLE
lsp haskell incredibly slow on latest emacs git

### ISSUE THREAD

**Issue by patrickaldis** [emacs-lsp/lsp-haskell#158]
After updating to the latest emacs pgtk git build, `lsp-haskell` runs very slowly - with type annotations taking 2-3 seconds to load. Any idea what could have caused this?

hls runs fine from cmd, everything checks out - this is a project that I've been running fine previously on emacs 28

**Comment by yyoncho** [comment]
Here we have a guide how to report/diagnose perf issues: https://emacs-lsp.github.io/lsp-mode/page/performance/

**Comment by Cmdv** [comment]
I'm having the same issues here on doom/emacs but it's where running `lsp execute code action`

I ran `lsp-doctor` and this is the output:
```
Checking for Native JSON support: OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: OK
Byte compiled against Native JSON (recompile lsp-mode if failing when Native JSON available): OK
`gc-cons-threshold' increased?: OK
Using `plist' for deserialized objects? (refer to https://emacs-lsp.github.io/lsp-mode/page/performance/#use-plists-for-deserialization): OPTIONAL
Using emacs 28+ with native compilation?: OK
```

I couldn't grasp the rest of the instructions given I'm not savvy enough in emacs/lisp to quite grasp how I run the functions. :(

**Comment by natto1784** [comment]
i have the same issue on `GNU Emacs 30.0.50`

**Comment by Cmdv** [comment]
Interesting my [doom](https://github.com/doomemacs/doomemacs) is running on `GNU Emacs 28.2` but I did spot this:
```
lsp-request: Timeout while waiting for response.  Method: textDocument/codeAction
```

which seems to point to [HLS](https://haskell-language-server.readthedocs.io/en/latest/features.html) and I'm on `HLS 1.8.0.0` so for my case it seems to point to there 🤔

**Comment by natto1784** [comment]
My HLS is `haskell-language-server version: 1.7.0.0 (GHC: 9.0.2)`. Might we be onto something?

**Comment by Sp1r7t** [comment]
I have a similar problem but with typescript. When I install or build emacs with pgtk, code completion takes 3 - 5 seconds to load. But, as soon as I compile it without pgtk, everything works perfectly.

**Comment by tonicebrian** [comment]
In case it helps anyone reading this thread in my case, the problem was solved when I removed a remnant of the time I was playing with bazel. It was:

```
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-file-watch-ignored-directories "bazel-[^/\\\\]+\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "output[^/\\\\]+\\'")
  )
```
I guess this had some interaction with LSP although my project was a pure Stack based one and had nothing about bazel. But after removing this and with latest lsp the problem was gone.

**Comment by michaelpj** [comment]
Is this still happening for people? Did anyone work out what was going on?

**Comment by Cmdv** [comment]
@michaelpj seems fine here now. I can't recall if it was an update to lsp-haskell or hls that did the trick though!!

**Comment by michaelpj** [comment]
Sigh. well, at least it went away.
