### ISSUE TITLE
lsp-server exits with status 'exit'

### ISSUE THREAD

**Issue by GrumpyOldGandalf** [emacs-lsp/lsp-haskell#159]
I am using emacs with `lsp-haskell` in a nix project that sets the ghc version to 9.2.1.

`haskell-language-server` is present in the `$PATH` at the nix store location appropriate to that version of Haskell, afaict.

When I open a Haskell file in emacs, I get an error "Server lsp-haskell:14406/starting exited with status exit(check corresponding stderr buffer for details). Do you want to restart it? (y or n)". Restarting it is unsuccessful, giving the same error. A stderr does not seem to be opened in emacs for inspection.

How can I troubleshoot this?

**Comment by michaelpj** [comment]
There's a troubleshooting section of the README. The issue template even points you to it :) You probably want to follow the breadcrumbs to the HLS troubleshooting page: https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html
