### ISSUE TITLE
hie fails to launch if ghc is not on PATH (but stack is)

### ISSUE THREAD

**Issue by Technius** [emacs-lsp/lsp-haskell#16]
I use `stack` to handle all of my Haskell versioning, so I don't have a system GHC installed. I'm using spacemacs develop.

The `lsp-haskell stderr` buffer contains
```plain
/bin/sh: ghc: command not found
hie: readCreateProcess: ghc --version (exit 127): failed

Process lsp-haskell stderr finished
```

A workaround is to set `lsp-haskell-process-path-hie` to `hie-wrapper` (described [here](https://github.com/haskell/haskell-ide-engine#editor-integration)).

Edit: Would it be a good idea for `hie-wrapper` to become the default instead of `hie`?

**Comment by alanz** [comment]
The current hie master is supposed to not need ghc if stack is being used for the project, please make sure you are using the latest version.

And yes, hie-wrapper should be the default.
