### ISSUE TITLE
README missing a step?

### ISSUE THREAD

**Issue by glyn** [emacs-lsp/lsp-haskell#163]
After several hours of fiddling, I am under the impression I need to install the package haskell-mode to get lsp-haskell to work. If this really is necessary, then it seems the README of this repo is missing this instruction. Happy to create a PR if so...

**Comment by yyoncho** [comment]
`haskell-mode` can be a dependency as well to avoid that kind of issues. Similarly, lsp-dart depends on dart-mode.

**Comment by yyoncho** [comment]
In case it is not clear, feel free to provide a PR :)

**Comment by glyn** [comment]
Since my elisp knowledge would fit on a postage stamp with room to spare, please take a look at this draft PR: https://github.com/emacs-lsp/lsp-haskell/pull/164.
