### ISSUE TITLE
Question: how can I get rid of "Processing" message from modeline

### ISSUE THREAD

**Issue by Javran** [emacs-lsp/lsp-haskell#166]
My apologies in advance if this isn't the right place to ask this question - in fact I have no idea which project is responsible for this behavior.

I notice that, as I start typing in a `.hs` file, there's a "⌛ Processing" flashing up and disappearing very frequently in the modeline, like this one: 
![rCRzStg](https://user-images.githubusercontent.com/1096354/213998301-b309ed7d-de77-421b-b519-97611921317d.png)
 and this gets annoying very quickly.

I've tried turning off everything that looks like "lsp-modeline-*-mode" but none seem to be the right switch.

**Comment by yyoncho** [comment]
Change `lsp-progress-function`  to `identity`

**Comment by Javran** [comment]
Thanks for the quick response!

**Comment by michaelpj** [comment]
To be fair, I also believe there may be a HLS bug here. I have long suspected that it does not report progress correctly, which sometimes leads to flickring progress notifications or sometimes just dead ones.
