### ISSUE TITLE
Timeout while waiting for response Method: textDocument/codeAction

### ISSUE THREAD

**Issue by Cmdv** [emacs-lsp/lsp-haskell#167]
My setup is:
macos m1
emacs/doom (28.2)
haskell-language-server version: 1.9.1.0 (GHC: 9.2.5)

I have the following logs but can't quite work out where things are failing, if I could have advice on how I might be able to diagnose this further it would be great. :)

I even downloaded vscode!!! 😅 frustratingly everything works fine there :(

The backtrace:
```
Debugger entered--Lisp error: (error "Timeout while waiting for response.  Method: textDocument/codeAction")
  error("Timeout while waiting for response.  Method: %s" "textDocument/codeAction")
  lsp-request("textDocument/codeAction" (:textDocument (:uri "file:///Users/cmdv/Code/Data/HDT...") :range (:start (:line 14 :character 18) :end (:line 14 :character 18)) :context (:diagnostics [#<hash-table equal 4/4 0x48259521>])))
  lsp-code-actions-at-point()
  byte-code("\300\301 !C\207" [lsp--select-action lsp-code-actions-at-point] 2)
  #<subr call-interactively>(lsp-execute-code-action nil nil)
  apply(#<subr call-interactively> (lsp-execute-code-action nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> lsp-execute-code-action nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (lsp-execute-code-action nil nil))
  call-interactively(lsp-execute-code-action nil nil)
  command-execute(lsp-execute-code-action)
```

`lsp-doctor` seems to be fine
```
Checking for Native JSON support: OK
Check emacs supports `read-process-output-max': OK
Check `read-process-output-max' default has been changed from 4k: OK
Byte compiled against Native JSON (recompile lsp-mode if failing when Native JSON available): OK
`gc-cons-threshold' increased?: OK
Using `plist' for deserialized objects? (refer to https://emacs-lsp.github.io/lsp-mode/page/performance/#use-plists-for-deserialization): OPTIONAL
Using emacs 28+ with native compilation?: OK
```

**Comment by michaelpj** [comment]
If the request is timing out that sounds like a server issue.

**Comment by Cmdv** [comment]
so more likely to be the LSP server, just it doesn't output anything of interest when I look at the LSP logs anyways.

There's been a bunch of updates in the doomemacs repo and as part of that it seems to have fixed the issue!!! Think it might have been an update in version of `lsp-mode` which forced `lsp-haskell` to rebuild.

Not 100% I need to improve on my Lisp 😅 

Either ways it's not seems to all work well, been living with it like this for about 3-4 months too 😂 

I'll close this for now 👍
