### ISSUE TITLE
[QUESTION] Line breaker after constraints for type lenses

### ISSUE THREAD

**Issue by hellwolf** [emacs-lsp/lsp-haskell#178]
![image](https://github.com/emacs-lsp/lsp-haskell/assets/186660/3ddd7275-e642-4071-a7d6-333788a94949)

As illustrated above, it seems the codeLens of "ghcide-type-lenses"(?) break the lines right after the constraints section (after "=>"). Is it a known behavior?

**Comment by michaelpj** [comment]
Hi, I think this is a HLS issue, please open an issue there.
