### ISSUE TITLE
Don't use the debug flag by default.

### ISSUE THREAD

**Issue by trivialfis** [emacs-lsp/lsp-haskell#179]
Hi all, https://github.com/emacs-lsp/lsp-haskell/blob/c443f1536404c252dbd16cf44eb47cabdcd6c45f/lsp-haskell.el#L438 enables the debug flag by default, which causes the language server to dump log to disk and become unresponsive. I think for most of the use cases, the debug flag is unnecessary. I can help remove the flag from default if this sounds reasonable.

**Comment by michaelpj** [comment]
Yeah, I agree that that seems like a mistake. I think it's probably helpful to have a logfile by default, but maybe even that is too opinionated?

**Comment by trivialfis** [comment]
Thank you for the reply. The log file is fine.

**Comment by trivialfis** [comment]
I opened an oneliner fix here: https://github.com/emacs-lsp/lsp-haskell/pull/180 .
