### ISSUE TITLE
QUESTION: always send tabSize=8 when formatting code？

### ISSUE THREAD

**Issue by nasyxx** [emacs-lsp/lsp-haskell#20]
When I format my code with <kbd>M-x lsp-format-buffer</kbd>, it always sends a json with

```
{
  ...,
    "options": {
      "tabSize": 8,
      "insertSpaces": true
    }
  ...
}
```

Is this a normal behavior?

And how can I ignore the tabSize option?

**Comment by alanz** [comment]
I think this issue should be tracked against https://github.com/emacs-lsp/lsp-mode

**Comment by nasyxx** [comment]
Thank you! I found it: 

https://github.com/emacs-lsp/lsp-mode/blob/3ed4cee1b688be574cc557327e2bc76aa0f23dff/lsp-methods.el#L1864

Just simply `(setq tab-width 4)`.
