### ISSUE TITLE
Timeouts while waiting for responses

### ISSUE THREAD

**Issue by langston-barrett** [emacs-lsp/lsp-haskell#28]
Hi, I'm trying to integrate HIE/LSP with Spacemacs. The server is starting and communicating with Emacs (in particular hlint suggestions and refactor buttons are showing, presumably via LSP-UI). However, meaningful edits such as `rename` and `lift` cause:
```
Timed out while waiting for a response from the language server [2 times]
```
I'm using Emacs 26.1 on NixOS. 
```
> hie --version
Version 0.2.2.0 x86_64 ghc-8.4.3
```
Full log here: [hie.log](https://github.com/emacs-lsp/lsp-haskell/files/2546331/hie.log)

Any idea what might be happening? Any help is appreciated!

**Comment by thkoch2001** [comment]
Please check the buffer *lsp-haskell stderr*. For me it contained:

```
hie: Could not find $libexecdir/cabal-helper-wrapper

If you are a cabal-helper developer you can set the environment variable
`cabal_helper_libexecdir' to override $libexecdir[1]. The following will
work in the cabal-helper source tree:

    $ export cabal_helper_libexecdir=$PWD/dist/build/cabal-helper-wrapper

[1]: /usr/lib

If you don't know what I'm talking about something went wrong with your
installation. Please report this problem here:

    https://github.com/DanielG/cabal-helper/issues
```

I set the variable to a location where this binary was compiled to inside the haskell-ide-engine git checkout, in my case 

    /git/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-12.17/8.4.4/libexec/x86_64-linux-ghc-8.4.4/cabal-helper-0.8.0.4

Now it works.
I still need to dig deeper what this binary does and how this experience can be made better for users of a Debian package for lsp-haskell.

**Comment by alanz** [comment]
You should be installing hie under nix using https://github.com/domenkozar/hie-nix

**Comment by siddharthist** [comment]
@alanz That is what I'm using. Thanks for the pointer, though (and your hard work, of course!)

**Comment by michaelpj** [comment]
I think this got tracked down to an issue with launching the language server, and followed up elsewhere.
