### ISSUE TITLE
How to enable? (aka What happened to lsp-haskell-enable?)

### ISSUE THREAD

**Issue by simendsjo** [emacs-lsp/lsp-haskell#31]
The documentation states that we should add the following to the configuration: `(add-hook 'haskell-mode-hook #'lsp-haskell-enable)`. Unfortunately, I cannot find this prodcedure.

**Comment by simendsjo** [comment]
Looks like it works if I just enable lsp-mode. Closing this. The documentation should probably be updated though.

**Comment by simendsjo** [comment]
Scratch that. Looks like something works, but the hie server doesn't start. So I'm back at "unable to start lsp-haskell" :)

**Comment by simendsjo** [comment]
If I manually evaluate the following from lsp-haskell.el, it works:

``` emacs-lisp
(lsp-define-stdio-client lsp-haskell "haskell" #'lsp-haskell--get-root
			 ;; '("hie" "--lsp" "-d" "-l" "/tmp/hie.log"))
       ;; '("hie" "--lsp" "-d" "-l" "/tmp/hie.log" "--vomit"))
       (funcall lsp-haskell-process-wrapper-function (lsp--haskell-hie-command)))
```
So I'm able to copy this to my config to work around the issue.

**Comment by iAmMrinal0** [comment]
@simendsjo Could you share where in your config do you add the snippet? I tried it and it didn't seem to work, unfortunately. It's getting difficult to run into this error while I'm trying to solve merge conflicts mainly, as the mode doesn't get loaded.

**Comment by simendsjo** [comment]
The issue is more than a year old, so I don't have much memory of it as I never got it working. Feel free to close the issue.

**Comment by michaelpj** [comment]
Please reopen if you have this trouble again with the setup in the README!
