### ISSUE TITLE
Syntax highlighting in popups does not work

### ISSUE THREAD

**Issue by svenkeidel** [emacs-lsp/lsp-haskell#43]
First of all, thanks for the great project, I'm enjoying lsp-haskell. I don't know if this is the right place file this issue. I successfully installed `lsp-mode` `lsp-ui` and `lsp-haskell`, but the pop ups that appear on hovering over code are not properly formatted:
![2019-06-06-093116_1069x157_scrot](https://user-images.githubusercontent.com/266500/59015008-3d576b80-883e-11e9-95d1-019ef5c889ba.png)

I'm running emacs on nixos. Here is my emacs config:
```elisp
(req-package haskell-mode
  :require lsp lsp-haskell flycheck smartparens
  :init
    (setq haskell-process-type 'stack-ghci
          haskell-tags-on-save t)
    (add-hook 'haskell-mode-hook 'flycheck-mode)
    (add-hook 'haskell-mode-hook 'smartparens-strict-mode)
    (add-hook 'haskell-mode-hook 'haskell-indent-mode)
    (add-hook 'haskell-mode-hook 'linum-mode)
    (add-hook 'haskell-mode-hook 'lsp))

(req-package lsp-mode
  :require lsp-ui
  :config
    (add-hook 'lsp-mode-hook 'lsp-ui-mode))
```
Any ideas?

Regards,
Sven

**Comment by alanz** [comment]
I think you may need to 

```
(require 'markdown-mode)
```

as well. Which should probably be included in `lsp-ui` or some other.

**Comment by svenkeidel** [comment]
No, this does not do the trick. I added `(require 'markdown-mode)` to the `haskell-mode`, `lsp-mode` and `lsp-ui` config. The popups are still not formatted.

**Comment by svenkeidel** [comment]
I switched to Spacemacs, which fixed the issue.
