### ISSUE TITLE
Support for literate-haskell-mode.

### ISSUE THREAD

**Issue by Anton-Latukha** [emacs-lsp/lsp-haskell#49]
Have a bunch of projects in literate Haskell. The most bare-bones variant:
  * `.lhs` file extensions
  * `\begin{code}` & `\end{code}` blocks inside them.
Having a highlighting support, Haskell toolkits handle projects/code ordinary.

Configured Emacs with HIE. `.hs` project work fully. `.lhs` projects recieving:
>  LSP :: No LSP server for literate-haskell-mode.

Tried to add hooks to `literate-haskell-mode` in two forms:

```elisp
(add-hook 'literate-haskell-mode-hook #'lsp-haskell-enable)
(add-hook 'literate-haskell-mode-hook #'lsp)
```

So far not got any progress.
Seems like should be a sure simple thing. Do not know is it Emacs `lsp-haslell` or `HIE` issue.

**Comment by michaelpj** [comment]
I think this would just require adding `haskell-literate-mode` (which seems to be what `literate-haskell-mode` is now called) to the `major-modes` that we register as supporting. I guess it doesn't work automatically despite `haskell-literate-mode` being derived from `haskell-mode`.

**Comment by Anton-Latukha** [comment]
Thank you.
