### ISSUE TITLE
Shouldn't hie-wrapper be started in the root directory?

### ISSUE THREAD

**Issue by Ptival** [emacs-lsp/lsp-haskell#51]
I have a setup where my project looks like:
```
`- project
  `- backend
    `- project.cabal
    `- stack.yaml
  `- frontend
    `- stuff.js
```

Sadly, LSP Haskell fails to start in this setting, because `hie-wrapper` is started in the `project` directory, rather than in the `backend` directory.

`lsp-haskell--get-root` correctly returns the `backend` directory, but this function does not seem to be used, as much as it seems to be provided as a convenience for `lsp-haskell-process-wrapper-function`.

However, I wonder whether it would not always be preferrable to start `hie-wrapper` in the project returned by `lsp-haskell--get-root`. It would readily solve my issue, and I believe it would also work correctly for the "simpler" setup where the `project` directory is also the `root` directory.

**Comment by Ptival** [comment]
Note: this was harder than I thought.

Essentially you need to modify `lsp-haskell-process-wrapper-function` **before** the Haskell mode starts, so that the command sent to the server is correct.

But the value of `lsp-haskell--get-root` is `.` until the Haskell mode has started.

My personal workaround is to have a hook to set `lsp-haskell-process-wrapper-function` **before** the Haskell mode starts, defining it as:

```
(lambda (argv)
  (append argv (list "-r" (haskell-cabal-find-dir default-directory))))
```

**Comment by Ptival** [comment]
Somehow things seem worse now. When I enter a Haskell buffer, `lsp-haskell--hie-command` seems to be called twice:
- once from the file that I opened (in which case my workaround works)
- then, a second time, from my project directory (which is bad: I no longer know which file is being processed)

**Comment by Ptival** [comment]
The following repository lets one reproduce the issue:

https://github.com/Ptival/mock-haskell-project-02/tree/7b3e875347bae083ec5975e1b32dfea9373c439d

If you try to open a Haskell file from this repository, HIE will be started in the root directory, rather than in the `not-root` directory, and thus will fail to figure out which GHC to use and crash.

**Comment by Ptival** [comment]
The main issue I see is that LSP runs commands from the projectile project root, but hie-wrapper needs to be ran either from the directory that contains the cabal file, or be given such directory with the `-r` option.

**Comment by Ptival** [comment]
Fixed by:

```
(add-hook! 'haskell-mode-hook
  (setq lsp-haskell-process-args-hie (list "-d" "-l" "/tmp/hie.log" "-r" (haskell-cabal-find-dir))))
```

I feel like this could be the default value.

**Comment by tonyday567** [comment]
Had the same issue.  

I also had to clear the .emacs.d/.lsp-session-v1 cache to remove prior incorrect root information.

**Comment by alanz** [comment]
The behaviour in hie/ghcide/hls changed, it used to detect from the root directory given in the LSP protocol initialisation, but now expects to be in the given directory.  Will update.

**Comment by FranklinChen** [comment]
I'm using hls 0.3.0 and there seems no "-r" option but the following worked for me:

```
(add-hook 'haskell-mode-hook
          (lambda ()
            (setq lsp-haskell-process-args-hie (list "-d" "-l" "/tmp/hie.log" "--cwd" (haskell-cabal-find-dir)))))
```

**Comment by michaelpj** [comment]
Looking in `lsp-mode`, it seems that this issue [comes up frequently](https://github.com/emacs-lsp/lsp-mode/issues/1978#issuecomment-664814859). Their position seems to be:
- You should get an interactive choice of root, which gives you the option to pick where the right root is.
- As far as `lsp-mode` guessing the root goes, they delegate to `projectile` which apparently has hooks for configuring that.

So I think we *shouldn't* implement logic ourselves for this.
