### ISSUE TITLE
eldoc support?

### ISSUE THREAD

**Issue by mohkale** [emacs-lsp/lsp-haskell#52]
I'm having difficulty getting eldoc to show type hints in the echo area? I'm not really that familliar with haskell as a language, but I'd expect anything the built in haskell mode can show type hints for, the lsp-haskell wrapper should do so as well. For example, if I create a simple haskell file like this in an empty directory:

```haskell
module Main (main) where

main :: IO ()
main = putStrLn "Hello, World!"
```

when I hover over `putStrLn` nothing is echoed. If I type `M-: (lsp-eldoc-function)` nil is printed to the messages buffer so I can only surmise HIE/the-language-server doesn't know what the definition or declaration of `putStrLn` is. but if I do `M-x lsp-describe-thing-at-point` a new buffer pops up and displays

```

putStrLn :: String -> IO ()
putStrLn :: String -> IO ()


The same as putStr, but adds a newline character.



base System.IO
```

so the server does know what the definition is, it just doesn't seem willing to echo it. (Notice the leading empty line in the response, I suspect it may have something to do with this but I can't be sure). What's more, if I use the built in haskell-mode doc function by typing `M-: (haskell-doc-current-info)` `putStrLn :: String -> IO ()` is echoed out.

my value of `eldoc-documentation-function` is:

```
#[128 "\300\301\"\206\0\300\302\"\207" [apply lsp-eldoc-function
      haskell-doc-current-info nil] 4 nil]
```

and I have no idea how to decipher it, but I don't think that's the reason `lsp-eldoc-function` returns nil anyways. I've got lsp-mode setup and working with kotlin so I know it can work with eldoc... I'm just not sure how to get it working with haskell. Any help would be appreciated here.

I'm running hie `Version 0.12.0.0, Git revision 098b1800c16ec1348fe9d380b946ec4ffa884f38 (3005 commits) x86_64 ghc-8.6.5`.

**Comment by michaelpj** [comment]
It sounds like the issue here is support for the `signatureHelp` requests in the language server, i.e. `haskell-language-server`. If the server supports it then `lsp-mode` should do the right thing. Could you open an issue in `haskell-language-server`, please (assuming it hasn't been fixed already)?
