### ISSUE TITLE
Hovering on the parameter of a lambda shows the type of the lambda not the parameter

### ISSUE THREAD

**Issue by ssbothwell** [emacs-lsp/lsp-haskell#54]
I would expect to get the type of the parameter rather then the type of the full lambda when highlighting the parameter specifically. Here are a couple examples where it happens:

```
data Cont r a = Cont ((a -> r) -> r)
instance Functor (Cont r) where
  fmap f (Cont g) = Cont $ \br -> g (br . f)

f :: Int -> ()
f = \i -> ()

g = (\p -> ()) :: Bool -> ()
```

I'm using spacemacs with the LSP layer, Haskell layer, LSP-haskell, and ghcide.

**Comment by michaelpj** [comment]
Hi, if you can still reproduce this it's an issue for haskell-language-server. lsp-haskell just forwards on the messages that we get from there.
