### ISSUE TITLE
Relevant Bindings are stripped out of the type hole warning popup

### ISSUE THREAD

**Issue by ssbothwell** [emacs-lsp/lsp-haskell#55]
When I hover on a type hole, I get a popup on the right side of the window with the type hole's shape, however the relevant bindings are stripped out of the popup. There is plenty of room on the screen to display the full warning.

To be honest, i'm not totally sure if this is an issue with LSP-Haskell or some other package in this tool chain.

I'm using spacemacs, LSP-Layer, Haskell-Layer, LSP-Haskell, and GHCIDE.

**Comment by michaelpj** [comment]
Hi, if you can still reproduce this it's an issue for `haskell-language-server`. `lsp-haskell` just forwards on the messages that we get from there.
