### ISSUE TITLE
Remove the --lsp hie param

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-haskell#58]
It has just been removed in master, wait for it to become present in the next release, and then remove it.

Probably not before 2020-02-15

ref: https://github.com/haskell/haskell-ide-engine/pull/1494

**Comment by thblt** [comment]
In my experience (hie 1.0.0.0/NixOS unstable), `--lsp` is now required for the server to work correctly. I just had an issue with both eglot and lsp that I solved by adding the `--lsp` flag in eglot program list. Haven't tested with lsp-mode though.

**Comment by alanz** [comment]
Yes, we brought it back, to harmonise with the ghcide approach
