### ISSUE TITLE
Warnings pop up

### ISSUE THREAD

**Issue by wraithm** [emacs-lsp/lsp-haskell#59]
I keep getting warning pop ups in the "*Warnings*" buffer with the following warning:

```
Warning (lsp-mode): Unknown request method: window/workDoneProgress/create
Warning (lsp-mode): Unknown request method: window/workDoneProgress/create
Warning (lsp-mode): Unknown request method: window/workDoneProgress/create
```

Any idea what's going on here?

**Comment by ashkan-leo** [comment]
Same issue here

**Comment by d12frosted** [comment]
The same issue. As a temporary workaround - `(setq warning-minimum-level ':error)`.

**Comment by michaelpj** [comment]
Looking at the linked issues, it seems that this was solved. Please reopen if not!
