### ISSUE TITLE
Make hie startup multi-platform

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-haskell#6]
At the moment, as per https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el#L253, we have

```elisp
(lsp-define-stdio-client lsp-haskell "haskell" #'lsp-haskell--get-root
   '("hie" "--lsp" "-d" "-l" "/tmp/hie.log"))
```
Where the log path is hard coded for something on linux.

This should be platform-aware, for windows and osx.

**Comment by alanz** [comment]
Probably `(expand-file-name "hie.log" temporary-file-directory)`, as suggested on IRC by @mxf

**Comment by oscarvarto** [comment]
I'm hitting this problem on Windows 10
