### ISSUE TITLE
haskell-mode errors mix with lcp-haskell errors?

### ISSUE THREAD

**Issue by Martinsos** [emacs-lsp/lsp-haskell#61]
It seems that even when lcp-haskell has no errors to report, I am getting errors directly from haskell-mode (which reports errors that are not really there, since it does not care about stack project and extensions and similar). 

I describe my situation more here: https://github.com/haskell/haskell-ide-engine/issues/1544 .

I have to admit, I am not sure cause of the problem is what I mentioned above, but it is my best guess at the moment. I am going crazy here trying to debug this - if you could help me eliminate this as a cause or help me fix it, that would mean a lot! Thanks.

**Comment by Martinsos** [comment]
```
(req-package lsp-mode
  :ensure t
  :config
  (progn
    (setq lsp-document-sync-method 'full) ;; To make sure documents don't get out of sync regarding parse errors.
    ))

(req-package lsp-haskell
  :ensure t
  :require lsp haskell-mode
  :config
  (progn
    (add-hook 'haskell-mode-hook #'lsp)
    ))

(req-package lsp-ui
  :ensure t
  :require lsp-mode
  :config
  (progn
    (add-hook 'lsp-mode-hook 'lsp-ui-mode)
    (add-hook 'haskell-mode-hook 'flycheck-mode)
    ))
```

**Comment by michaelpj** [comment]
Not sure if you're seeing this still, but I found I needed to turn off the default checker that flycheck provides for Haskell. Like so (in `custom-set-variables`):
```
'(flycheck-disabled-checkers '(haskell-stack-ghc haskell-ghc))
```

Does this help you?

**Comment by Martinsos** [comment]
Thanks @michaelpj , yes I am sure that would help! I switched in the meantime from my long-time vanilla emacs to spacemacs so I don't have this problem any more, although I am not using lsp but dante at the moment -> I so plan to try out lsp again when I catch some time, but I believe in spacemacs checkers will already be correctly configured.
Thanks, I am closing the issue!
