### ISSUE TITLE
Enable hlint on multi projects by default

### ISSUE THREAD

**Issue by marcellussiegburg** [emacs-lsp/lsp-haskell#69]
Is there a way of enabling hlint by default? I could not figure out how.
It seems there is no way of setting this within my `.emacs` file.
I know that I can call `lsp-haskell-set-hlint-on` on every file or setting file-local-variables (maybe even dir-local-variables?, though being unable to setting it up); but I want hlint being enabled always anyway.

**Comment by walseb** [comment]
Strange, on my PC it's always on by default. But if you want to run that in every new buffer you could probably just do `(add-hook 'haskell-mode-hook 'lsp-haskell-set-hlint-on)`

**Comment by marcellussiegburg** [comment]
Thank you very much. After trying different files I figured out the issue seems to persists with multi projects only, i.e. projects using a hie.yaml. Other projects work as expected.
