### ISSUE TITLE
Suppress minibuffer messages?

### ISSUE THREAD

**Issue by Javran** [emacs-lsp/lsp-haskell#72]
My stack project is currently having trouble building, hie.log keeps showing some error like below:

```
2020-06-19 18:00:29.309127386 [ThreadId 4844] - Source error on cradle initialisation: `gcc' failed in phase `C pre-processor'. (Exit code: 1)
```

However here the error message isn't my point, I want to emphasis on the plugin behavior: as the plugin retries* to build the project indefintely, my minibuffer is flooded with "Initializing Stack project...done", making it incredibly annoying and distracting:
![2020-06-19_180820_4480x1440_scrot](https://user-images.githubusercontent.com/1096354/85187877-f1644280-b257-11ea-9964-23bbb05bf1b2.jpg)

I want to see if there's a way that max retry times can be set, or this message can be suppressed so that it doesn't constantly show up.

*: actually I'm not sure if this retry behavior is in lsp-haskell, hie or something else.

**Comment by michaelpj** [comment]
There is a `lsp-restart` setting in `lsp-mode` that controls how to handle restarting the server when it crashes. I think that should be the right thing to fix on the emacs side.

On the language server side, if you're getting errors from the server (these days `haskell-language-server`), please raise some issues there!
