### ISSUE TITLE
Support HLS 0.2.2

### ISSUE THREAD

**Issue by Ailrun** [emacs-lsp/lsp-haskell#73]
Now HLS 0.2.2 uses the field name 'haskell' instead of 'languageServerHaskell'.

See https://github.com/haskell/haskell-language-server/releases/tag/0.2.2.

**Comment by shaunplee** [comment]
@Ailrun This is genuinely my first time trying to hack elisp. This seems to work for me (tried with HLS 0.2.2 and old version of HIE):

https://github.com/shaunplee/lsp-haskell

Can you give it a try before I submit a pull request, so that we have N>1?

**Comment by Ailrun** [comment]
Great, I will try it out and let you know as soon as I can access my PC.

**Comment by shaunplee** [comment]
Perhaps no longer needed due to a change in HLS? https://github.com/haskell/haskell-language-server/pull/243

**Comment by Ailrun** [comment]
Close this as HLS now support `languageServerHaskell` again.
