### ISSUE TITLE
lsp fails to start

### ISSUE THREAD

**Issue by kajus-park** [emacs-lsp/lsp-haskell#91]
When I try to start lsp following error message pops up:
![image](https://user-images.githubusercontent.com/69348089/99308634-89db0f00-2858-11eb-9f31-9f521fac96a7.png)

Eval: lsp-haskell-server-path 
"haskell-language-server-wrapper"

I am using doom Emacs with
:tools 
lsp
:lang 
(haskell +lsp +dante)

dante works fine, but I would like to have the lsp functionality too.

According to the README following should be sufficient
:tools
lsp
:lang
(haskell +lsp)

I have installed the server with ghcup.
Executing haskell-language-server-wrapper in the terminal gives some output, which I assume looks like it works.

I would appreciate some advice on this topic.

**Comment by michaelpj** [comment]
Have you looked in `lsp-log` as the message suggests?

**Comment by kajus-park** [comment]
Embarrassingly I was not able to figure out how to enable the logging of that.
When I do:
M-x lsp-switch-to-io-log-buffer 
I get:
IO logging is disabled

**Comment by michaelpj** [comment]
There should be a `lsp-log` buffer even without that.

**Comment by kajus-park** [comment]
I apologize for my stupidity. Yes the buffer was there. The command lsp-server-wrapper was not on path.
doom/reload-env fixed that.
Thank you for your patience.

**Comment by michaelpj** [comment]
No worries, glad you got it working!
